version: 2.1

workflows:
  node-tests:
    jobs:
      - lockfile-check
      - unit-tests:
          name: node18
          version: "18.0"
      - unit-tests:
          name: node20
          version: "20.0"
      - unit-tests:
          name: node22
          version: "22.0"
      - unit-tests:
          name: node24
          version: "24.0"

jobs:
  lockfile-check:
    docker:
      - image: cimg/node:24.0
    steps:
      - checkout
      - run:
          name: Check lockfile registry URLs
          command: npm run check-lockfile
  unit-tests:
    parameters:
      version:
        type: string
    docker:
      - image: cimg/node:<< parameters.version >>
    steps:
      - checkout
      - run:
          name: Node Version
          command: |
            echo "node: $(node --version)"
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Install typescript
          command: |
            npm install --no-save typescript@4.7.4
      - run:
          name: Run tests
          command: npm test
